spring:
  application:
    name: github

server:
  port: 8303

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost

sidecar:
  health-uri: https://api.github.com/users/