
spring:
  application:
    name: sidecar

server:
  port: 8303

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost


sidecar:
  port: 3000
  health-uri: http://localhost:3000/health.json
  hostname: http://localhost:3000

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 20
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000
