spring:
  application:
    name: discovery

server:
  port: 8300

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 20
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000