spring:
  application:
    name: search

server:
  port: 8302

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8300/eureka/
  instance:
    hostname: localhost

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
hystrix.command.default.execution.isolation.semaphore.maxConcurrentRequests: 20
ribbon:
  ConnectTimeout: 10000
  ReadTimeout: 60000